// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FUTEMAX HD - Futebol Online Grátis",
  description: "Assista futebol ao vivo grátis. Todos os jogos do Brasileirão, Champions League, Premier League e muito mais em alta qualidade.",
  keywords: "futebol online, futebol grátis, jogos ao vivo, brasileirão, champions league, premier league, la liga, bundesliga",
  openGraph: {
    title: "FUTEMAX HD - Futebol Online Grátis",
    description: "Assista futebol ao vivo grátis. Todos os jogos do Brasileirão, Champions League, Premier League e muito mais em alta qualidade.",
    type: "website",
    locale: "pt_BR",
    siteName: "FUTEMAX HD",
  },
  twitter: {
    card: "summary_large_image",
    title: "FUTEMAX HD - Futebol Online Grátis",
    description: "Assista futebol ao vivo grátis. Todos os jogos do Brasileirão, Champions League, Premier League e muito mais em alta qualidade.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "google-site-verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#dc2626" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        
        {/* Otimizações de Performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//sporturbo.com" />
        <link rel="dns-prefetch" href="//www.google-analytics.com" />
        
        {/* Cache Control */}
        <meta httpEquiv="Cache-Control" content="public, max-age=31536000, immutable" />
        
        {/* Schema.org structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "FUTEMAX HD",
              "description": "Assista futebol ao vivo grátis. Todos os jogos do Brasileirão, Champions League, Premier League e muito mais.",
              "url": "https://futemaxhd.com",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://futemaxhd.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
        
        {/* Service Worker para Cache Offline */}
        <Script id="service-worker" strategy="afterInteractive">
          {`
            if ('serviceWorker' in navigator) {
              window.addEventListener('load', function() {
                navigator.serviceWorker.register('/sw.js')
                  .then(function(registration) {
                    console.log('SW registered: ', registration);
                  })
                  .catch(function(registrationError) {
                    console.log('SW registration failed: ', registrationError);
                  });
              });
            }
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}